_target_:  pytorch_lightning.Trainer

max_epochs: 1000
accelerator: gpu
devices: [0, 3]
deterministic: False
detect_anomaly: False
enable_progress_bar: True
strategy: ddp
precision: 32
accumulate_grad_batches: 
val_check_interval: 2000
log_every_n_steps: 1
num_sanity_val_steps: 2
# Define callbacks
defaults:
  - logger: wandb

callbacks: "${oc.dict.values: callback}"